# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  sfml_game_dev_config = debug

else ifeq ($(config),release)
  sfml_game_dev_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := sfml-game-dev

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

sfml-game-dev:
ifneq (,$(sfml_game_dev_config))
	@echo "==== Building sfml-game-dev ($(sfml_game_dev_config)) ===="
	@${MAKE} --no-print-directory -C . -f sfml-game-dev.make config=$(sfml_game_dev_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f sfml-game-dev.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   sfml-game-dev"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"